### ISSUE TITLE
Network Error -- Aplication crashes

### ISSUE THREAD

**Issue by opensourceexpert** [IonicU/payuhybridappintegration#1]
Hey .. Thanks for creating this sample project. I tried to install this on my android device. As soon as I click on the button I the app crashes with an error "There was a network error https://test.payu.in/_payment"

Can you please help resolve this error?

**Comment by IonicU** [comment]
Hi.... @opensourceexpert thanks for installing it in android device.
Had you changed values in **payuBiz.html**  we need to change **txnid** and related **Hash** value.still if you face any issues let me inform....

**Comment by opensourceexpert** [comment]
Can you please help me how to generate Hash. I am facing issues there.

**Comment by IonicU** [comment]
By using this link [http://www.miniwebtool.com/sha512-hash-generator/](url) you can generate **Hash **value.
you have to generate **Hash **value from below formula
**gtKFFx|txn123fw|100|oxygenconcentrator|test|test@gmail.com|||||||||||eCwWELxi**
for every time we need to change  **txnid **

**Comment by opensourceexpert** [comment]
I am able to make the transaction using the correct params. I am able to reach the success url mentioned in params. How do I reach back in  the app with the success or faliure? Currently we stop on the success or faliure url.

Any pointers would be helpful.

**Comment by IonicU** [comment]
add this snippet of code where you want to close the Inappbrowser and redirect to your App 

`function iabLoadStop(event) {
//condition ckecking Inappbrowser url with success url
    if (event.url.match("https://payu.herokuapp.com/success")) {
	//Inappbrowser close 
	iabRef.close();
  }
}`

**Comment by opensourceexpert** [comment]
I tried this snippet but did not give the desired results. I am sure anyone using this sample app would need to close the browser and resturn to the success or faliure IONIC screen, so will it be possible for you to update this sample app.

Here is the exact scenerio:
After making the payment payu will redirect to the success or faliure URL in the in app browser. We can style that page as per the app look and feel. Depending on the success and faliure I want to close the inapp browser and open the respective IONIC screens in the app.

Thanks for all the help so far.

**Comment by IonicU** [comment]
@opensourceexpert  send your code where you feel hard i will help you...............

**Comment by opensourceexpert** [comment]
By anychance can I have your email address/cell number. I can call you. My
email addreess is aman.tech.expert@gmail.com.

**Comment by ShilpaSKavasseri** [comment]
Hey
Thank you for the code. Can you tell me how to capture the parameters that is being returned in the surl and furl? It would be of great help if you could solve :)

**Comment by IonicU** [comment]
@ShilpaSKavasseri  find the updated **app.js **  to capture the parameters that is being returned in the surl and furl

**Comment by IonicU** [comment]
Hi.... @opensourceexpert  had you find solution or still your facing any Issues regarding this....

**Comment by kopimn** [comment]
Hi ...Sai Thanks for the code its working fine. But I am totally clueless on changing the mode of payment. Can U help me in resolving it.

**Comment by ShilpaSKavasseri** [comment]
Hello
I am using cordova.InAppBrowser.open(). But the executeScript is not getting fired at all . Can you help me out?

**Comment by IonicU** [comment]
Hi.....
@opensourceexpert @ShilpaSKavasseri @kopimn  please post your code to my mail id **# sai.devcontact@gmail.com **

**Comment by IonicU** [comment]
@kopimn   I think your sending Same transaction Id with Same Hash Code....for every transaction we need to pass different Transaction ID with Hash. and one more thing you will get Failure URL  when transaction failed from PAYU team or Banks. other than that you always get Success URL.so you need to get response from success URL and based on Success response you can render whatever view you want.......

**Comment by mauriliofilho** [comment]
Hello, Sai CONGRATULATIONS at work, surely iso will help a lot of people trying to facilitate working with collection in mobile applications.
I did some adptações in your solution to use another gateway here by my parents "PagSeguro" in Brazil. Part of form submission Payment and shipping is okay, but the solution I use have to set up in the User paine the return urls.
a question these urls I need to create them on my server or can be in any hosting?
Another question, could help me in the question of the return of the solution I used so that I can capture the return?
Another rsrsrs question, I'm not sure I could do what I did for my adaptation work, but I am not managing to open the inappbrowser on the same screen of my app as your example does, it always opens with the Android browser, sending form are embedding on a screen which shows some data before sending to the payment screen.
I will add the email that you went there before the ateriores post to my repository if you are able to help me would be great.
